sudo: true
language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.26"
  - "blead"
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
  allow_failures:
    - perl: blead
before_install:
  - sudo apt-get update
  - sudo apt-get install ditaa
  - eval $(curl https://travis-perl.github.io/init) --auto
